### ISSUE TITLE
[Crash] NPE: Registry Object not present: waterdripsound:lavadrip

### ISSUE THREAD

**Issue by PieKing1215** [PieKing1215/WaterDripSound#1]
from https://www.curseforge.com/minecraft/mc-mods/waterdripsound?comment=11

only happens on multiplayer when the client has the mod but the server doesn't
no other mods necessary

```
java.lang.NullPointerException: Registry Object not present: waterdripsound:lavadrip
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:120) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.client.particle.DripParticle$LandingLavaFactory.handler$zhp001$createParticle(SourceFile:529) ~[?:?]
```

(basically `WaterDripSound.LAVA_DRIP_SOUND.get()` returns null)
the line that the crash happens on:
https://github.com/PieKing1215/DripSounds-Forge/blob/39444d36369f1914149da91237bc2c5c4b05b3f4/src/main/java/me/pieking1215/waterdripsound/mixin/client/MixinLandingLavaParticle.java#L29

**Comment by PieKing1215** [comment]
[v0.2.1](https://github.com/PieKing1215/DripSounds-Forge/releases/tag/v0.2.1) has a temporary workaround that prevents the crash but doesn't actually "fix" the problem
